messageFiles:

  - title: "API mediation common messages"
    file: ../../apiml-common/src/main/resources/apiml-common-log-messages.yml

  - title: "Common service core messages"
    file: ../../common-service-core/src/main/resources/mfs-common-messages.yml

  - title: "Security common messages"
    file: ../../apiml-security-common/src/main/resources/security-common-log-messages.yml

  - title: "Security client messages"
    file: ../../security-service-client-spring/src/main/resources/security-service-messages.yml

  - title: "Discovery service messages"
    file: ../../discovery-service/src/main/resources/discovery-service-log-messages.yml

  - title: "Gateway service messages"
    file: ../../gateway-service/src/main/resources/gateway-messages.yml


outputFile: ErrorMessagesDocumentation.md
