messageFiles:

  - title: "API mediation utility messages"
    file: ../../apiml-utility/src/main/resources/utility-log-messages.yml

  - title: "API mediation common messages"
    file: ../../apiml-common/src/main/resources/common-log-messages.yml

  - title: "Common service core messages"
    file: ../../common-service-core/src/main/resources/core-log-messages.yml

  - title: "Security common messages"
    file: ../../apiml-security-common/src/main/resources/security-common-log-messages.yml

  - title: "Security client messages"
    file: ../../security-service-client-spring/src/main/resources/security-client-log-messages.yml

  - title: "ZAAS client messages"
    file: ../../zaas-client/src/main/resources/zaas-client-log-messages.yml

  - title: "Discovery service messages"
    file: ../../discovery-service/src/main/resources/discovery-log-messages.yml

  - title: "Gateway service messages"
    file: ../../gateway-service/src/main/resources/gateway-log-messages.yml

  - title: "API Catalog messages"
    file: ../../api-catalog-services/src/main/resources/apicatalog-log-messages.yml


outputFile: ErrorMessagesDocumentation.md
