name: "Setup action"
description: "Prepares for execution - set up Java, Node, npm, Gradle"

inputs:
    jdkVersion:
        description: "JDK version"
        required: false
        default: "8"

runs:
    using: "composite"
    steps:
        -   name: Set up JDK ${{ inputs.jdkVersion }}
            uses: actions/setup-java@v4
            with:
                distribution: 'semeru'
                java-version: ${{ inputs.jdkVersion }}
        -   name: Set up Node
            uses: actions/setup-node@v4
            with:
                node-version: '18'
        -   run: npm install -g npm@9.3.1
            shell: bash
        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
            shell: bash

        -   name: Cache Gradle packages
            uses: actions/cache@v4
            with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

        -   name: Cache Node.js modules
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    **/node_modules
                key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
