version: "3.3"
services:
    api-catalog-services:
        image: ghcr.io/zowe/api-catalog-services:latest
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs
        ports:
            - "10014:10014"
    caching-service:
        image: ghcr.io/zowe/caching-service:latest
        ports:
            - "10016:10016"
    discoverable-client:
        image: ghcr.io/zowe/discoverable-client:latest
        ports:
            - "10012:10012"
    discovery-service:
        image: ghcr.io/zowe/discovery-service:latest
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs
        ports:
            - "10011:10011"
    gateway-service:
        image: ghcr.io/zowe/gateway-service:latest
        ports:
            - "10010:10010"
            - "10017:10017"
    mock-zosmf:
        image: ghcr.io/zowe/mock-zosmf:latest
        ports:
            - "10013:10013"
