#
# Static definition for z/OSMF running on system CA32 and port 1443
#
# To skip adding service certificate or CA certificate to the truststore
# of the API Gateway you need to see following setting in the
# config/local/gateway-service.yml:
#
#   apiml:
#       security:
#           verifySslCertificatesOfServices: false
#
#  Then you can access z/OSMF via the API gateway:
#
#   http --verify=keystore/local_ca/localca.cer GET https://localhost:10010/api/zosmfca32/zosmf/info 'X-CSRF-ZOSMF-HEADER;'
#
services:
    - serviceId: zosmfca32  # unique lowercase ID of the service
      title: IBM z/OSMF on CA32
      description: IBM z/OS Management Facility REST API service on CA32
      catalogUiTileId: zosmf
      instanceBaseUrls:  # list of base URLs for each instance
        - https://ca32.ca.com:1443  # scheme://hostname:port/contextPath
      homePageRelativeUrl:  # Home page is at the same URL
      routes:
        - gatewayUrl: api  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl: /
        - gatewayUrl: ui
          serviceRelativeUrl: /
      apiInfo:
        - apiId: com.ibm.zosmf
          gatewayUrl: api
          version: 2.3.0
          documentationUrl: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_RESTServices.htm

    - serviceId: zosmftso21  # unique lowercase ID of the service
      title: IBM z/OSMF on TSO21
      description: IBM z/OS Management Facility REST API service on TSO21
      catalogUiTileId: zosmf
      instanceBaseUrls:  # list of base URLs for each instance
        - https://tso21.ca.com:1443  # scheme://hostname:port/contextPath
      homePageRelativeUrl:  # Home page is at the same URL
      routes:
        - gatewayUrl: api  # [api/ui/ws]/v{majorVersion}
          serviceRelativeUrl: /
        - gatewayUrl: ui
          serviceRelativeUrl: /
      apiInfo:
        - apiId: com.ibm.zosmf
          gatewayUrl: api
          version: 2.3.0
          documentationUrl: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_RESTServices.htm


catalogUiTiles:
    zosmf:
        title: z/OSMF services
        description: IBM z/OS Management Facility REST services
