apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service

server:
    ssl:
        keyAlias: caching-service
        keyStore: keystore/docker/caching-service.keystore.p12
        trustStore: keystore/docker/caching-service.truststore.p12
