apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service

server:
    ssl:
        keyAlias: localhost
        keyStore: keystore/docker/all-services.keystore.p12
        trustStore: keystore/docker/all-services.truststore.p12
