apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service
        ssl:
            nonStrictVerifySslCertificatesOfServices: true
            verifySslCertificatesOfServices: false
