spring.profiles.include: diag

apiml:
    service:
        hostname: discovery-service
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/docker/api-defs
    security:
        ssl:
            verifySslCertificatesOfServices: false
    banner: console

spring:
    output:
        ansi:
            enabled: always

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: /docker/all-services.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: /docker/all-services.truststore.p12
        trustStorePassword: password

