server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/docker/all-services.keystore.p12
        keyStorePassword: password
        trustStore: keystore/docker/all-services.truststore.p12
        trustStorePassword: password
