spring.profiles.include: diag

apiml:
    service:
        hostname: localhost3
        ipAddress: 127.0.0.3
        port: 10031
    discovery:
        staticApiDefinitionsDirectory: config/local/api-defs
        allPeersUrls: https://localhost2:10021/eureka/,https://localhost3:10031/eureka/

spring:
    output:
        ansi:
            enabled: always

---
spring.profiles: https

apiml:
    discovery:
        allPeersUrls: https://localhost2:10021/eureka/,https://localhost3:10031/eureka/

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
