spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10012
        discoveryServiceUrls: https://localhost2:10021/eureka/,https://localhost3:10031/eureka/

spring:
    output:
        ansi:
            enabled: always

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/selfsigned/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/selfsigned/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12
