version: '3'

services:
    reverse:
        container_name: reverse
        hostname: reverse
        image: nginx
        ports:
            - 80:80
            - 10009:10009
        volumes:
            - ./conf:/etc/nginx
            - ../../keystore/localhost:/etc/ssl/private
