version: '3'

services:
    reverse:
        container_name: reverse
        hostname: reverse
        image: nginx
        ports:
            - 80:80
            - 10000:10000
            - 10001:10001
            - 10030:10030
            - 10016:10016
        volumes:
            - ./conf:/etc/nginx
            - ../../keystore:/etc/ssl/private
        extra_hosts:
            host.docker.internal: host-gateway
