eureka:
    client:
        serviceUrl:
            defaultZone: https://localhost:10011/eureka/

spring:
    application:
        name: ${apiml.service.id}

apiml:
    gateway:
        timeout: 60
    service:
        apimlId: apiml1
        id: cloud-gateway
        port: 10023
        hostname: localhost
        scheme: https  # "https" or "http"
        corsEnabled: true
        ignoredHeadersWhenCorsEnabled: Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers,Access-Control-Allow-Credentials,Origin
    security:
        ssl:
            nonStrictVerifySslCertificatesOfServices: true
    cloudGateway:
        serviceRegistryEnabled: false

server:
    port: ${apiml.service.port}
    ssl:
        clientAuth: want
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
    application:
        name: cloudGateway
    main:
        allow-circular-references: true

logbackServiceName: ZWEACG1

logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG
        reactor.netty.http.client.HttpClientConnect: OFF

management:
    endpoint:
      gateway:
          enabled: true
    endpoints:
        web:
            base-path: /application
            exposure:
                include: health,gateway
