eureka:
    client:
        serviceUrl:
            defaultZone: https://localhost:10011/eureka/

apiml:
    gateway:
        timeout: 60
    service:
        id: cloud-gateway
        port: 10023
        hostname: localhost
        gateway:
            proxy:
                enabled: true
    security:
        ssl:
            nonStrictVerifySslCertificatesOfServices: true
server:
    port: ${apiml.service.port}
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
        loadbalancer:
            retry:
                enabled: true
                max-retries-on-next-service-instance: 5
                max-retries-on-same-service-instance: 0
                retryable-status-codes: 503
                retry-on-all-operations: false
    application:
        name: cloudGateway

logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG

management:
    endpoint:
      gateway:
          enabled: true
    endpoints:
        web:
            base-path: /application
            exposure:
                include: health,gateway
