spring.profiles.include: diag

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1
    instance:
        leaseExpirationDurationInSeconds: 6
        leaseRenewalIntervalInSeconds: 1

server:
    ssl:
        enabled: true
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10014
        discoveryServiceUrls: https://usilca32.lvn.broadcom.net:7553/eureka/
        dsIpAddress: 0.0.0.0
        eurekaPassword: password
        eurekaUserName: eureka
        gatewayHostname: https://usilca32.lvn.broadcom.net:7554
        preferIpAddress: false

    service-registry:
        cacheRefreshInitialDelayInMillis: 10000
        cacheRefreshRetryDelayInMillis: 10000
        cacheRefreshUpdateThresholdInMillis: 120000
        serviceFetchDelayInMillis: 10000
    banner: console
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs

spring:
    config:
        useLegacyProcessing: true
    output:
        ansi:
            enabled: always

