spring.profiles.active: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
    security:
        ssl.verifySslCertificatesOfServices: true
    banner: console

spring.output.ansi.enabled: always

---
spring.config.activate.on-profile: https

apiml:
    discovery:
        allPeersUrls: https://${apiml.service.hostname}:10021/eureka/

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
