spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10012
        discoveryServiceUrls: http://eureka:password@localhost:10011/eureka/

spring:
    output:
        ansi:
            enabled: always
