spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10011
    discovery:
        staticApiDefinitionsDirectory: config/local/api-defs

spring:
    output:
        ansi:
            enabled: always
