spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10012
        discoveryServiceUrls: https://localhost:10011/eureka/

spring:
    output:
        ansi:
            enabled: always

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        # keyStore: keystore/selfsigned/localhost.keystore.p12        
        # keyStore: keystore/selfsigned/localhost-untrusted.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        # trustStore: keystore/selfsigned/localhost.truststore.p12
        # trustStore: keystore/selfsigned/localhost-untrusted.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12
