spring:
    profiles:
        include: diag
    output:
        ansi:
            enabled: always

# The `apiml` node contains API Mediation Layer specific configuration
apiml:
    service:
        # The `apiml.service` node contains information required by any APIML service
        serviceId: discoverableclient  # Service ID of this service
        hostname: localhost  # Hostname that is advertised in Eureka. Default is valid only for localhost
        port: 10012  # Default port for discoverable-client service
          # IP address that is advertised in Eureka. Default is valid only for localhost
        discoveryServiceUrls: https://localhost:10011/eureka/

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1
server:
    ssl:
        keyAlias: apiml
        keyPassword: password
        keyStore: ../keystore/ca3x/apiml.keystore.p12
        keyStorePassword: password
        trustStore: ../keystore/ca3x/apiml.truststore.p12
        trustStorePassword: password
