spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
    security:
        ssl:
            nonStrictVerifySslCertificatesOfServices: true
    banner: console

spring:
    output:
        ansi:
            enabled: always

---
spring.profiles: https
eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1

server:
    ssl:
        keyAlias: apiml
        keyPassword: password
        keyStore: ../keystore/ca3x/apiml.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: ../keystore/ca3x/apiml.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12
