spring.profiles.include: diag

environment:
    discoveryLocations: http://eureka:password@localhost:10011/eureka/
    dsIpAddress: 127.0.0.1
    gatewayHostname: localhost
    gatewayTimeoutInMillis: 30000
    hostname: localhost
    ipAddress: 127.0.0.1
    keyAlias: localhost
    keyPassword: password
    keystoreType: PKCS12
    keystore: keystore/localhost/localhost.keystore.p12
    keystorePassword: password
    port: 10010
    preferIpAddress: false
    scheme: https
    sslEnabled: true
    truststore: keystore/localhost/localhost.truststore.p12
    truststorePassword: password
    truststoreType: PKCS12

mfaas:
    gateway:
        verifySslCertificatesOfServices: false

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseExpirationDurationInSeconds: 6
        leaseRenewalIntervalInSeconds: 5

spring:
    output:
        ansi:
            enabled: always
