spring.profiles.include: diag
apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10010
        discoveryServiceUrls: http://localhost:10011/eureka/
    security:
        auth:
            provider: dummy
            zosmf:
                serviceId: mockzosmf  # Replace me with the correct z/OSMF service id
            passTicket:
                timeout: 360 # [s] - default timeout to expire (z/OS has 10 mins as default)
        ssl:
            verifySslCertificatesOfServices: true
        x509:
            enabled: true
    banner: console

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1
spring:
    output:
        ansi:
            enabled: always
    cache:
        ehcache:
            config: classpath:ehcache.xml

server:
    internal:
        enabled: false

