eureka:
  ssl: true
  host: localhost
  ipAddress: 127.0.0.1
  port: 10011
  servicePath: '/eureka/apps/'
  maxRetries: 30
  requestRetryDelay: 1000
  registryFetchInterval: 5


instance:
  app: hwexpress
  vipAddress: hwexpress
  instanceId: localhost:hwexpress:10020
  homePageUrl: https://localhost:10020/
  hostName: 'localhost'
  ipAddr: '127.0.0.1'
  secureVipAddress: hwexpress
  port:
    $: 10020
    '@enabled': false
  securePort:
    $: 10020
    '@enabled': "true"

  dataCenterInfo:
    '@class': com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo
    name: MyOwn
  metadata:
    apiml.catalog.tile.id: 'cademoapps'
    apiml.catalog.tile.title: 'Sample API Mediation Layer Applications'
    apiml.catalog.tile.description: 'Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem'
    apiml.catalog.tile.version: '1.0.0'
    apiml.routes.api_v1.gatewayUrl: "api/v1"
    apiml.routes.api_v1.serviceUrl: "/api/v1"
    apiml.apiInfo.0.apiId: org.zowe.hwexpress
    apiml.apiInfo.0.gatewayUrl: "api/v1"
    apiml.apiInfo.0.swaggerUrl: https://localhost:10020/swagger.json
    apiml.service.title: 'Zowe Sample Node Service'
    apiml.service.description: 'The Proxy Server is an HTTP HTTPS, and Websocket server built upon NodeJS and ExpressJS.'

ssl:
  certificate: ../keystore/localhost/localhost.keystore.cer
  keystore: ../keystore/localhost/localhost.keystore.key
  caFile: ../keystore/localhost/localhost.pem
  keyPassword: password
