name: "Setup for image publishing action"
description: "Prepares for image publishing"

inputs:
    imageVersion:
        description: "Image version to be published"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        -   uses: ./.github/actions/setup

        -   name: Set gradle.properties version
            # images publish with the version in gradle.properties
            # if a version is provided, use that version to publish, else use value in gradle.properties
            if: ${{ inputs.imageVersion != '' }}
            shell: bash
            run: sed -i 's/version=.*/version=${{ inputs.imageVersion }}/g' gradle.properties

        -   uses: zowe-actions/shared-actions/prepare-workflow@main
