# +++++++++++++++++++++++++++++++++++++++++++++++++++
#
# THIS IS THE CORRECT FORMAT
#
#
# +++++++++++++++++++++++++++++++++++++++++++++++++++

modules:
  jmeter:
    gui: false

settings:
  artifacts-dir: test-results/%Y-%m-%d_%H-%M-%S.%f

execution:
- concurrency: 1
  hold-for: 1m
  scenario: sdk-jwt

# reporting:
# - module: final-stats
#   summary: true  # overall samples count and percent of failures
#   percentiles: true  # display average times and percentiles
#   summary-labels: true # provides list of sample labels, status, percentage of completed, avg time and errors
#   failed-labels: true  # provides list of sample labels with failures
#   test-duration: true  # provides test duration

scenarios:
  sdk-jwt:
    script: david-caching-profiling.jmx
    variables:
      host: usilca32.lvn.broadcom.net
      port: 7994
      USERNAME: janda06
      PASSWORD: Heslo234

# bzt 2020-sdk-jwt.yml -o settings.artifacts-dir=test-results/prodzowe-sdk-jwt
# bzt 2020-myapiml-sdk-jwt.yml -o settings.artifacts-dir=test-results/myzowe-sdk-jwt-20concurrent
# bzt 2020-myapiml-sdk-jwt.yml -o settings.artifacts-dir=test-results/myzowe-sdk-jwt-zaas-httpclient-optimized
# bzt 2020-myapiml-sdk-jwt.yml -o settings.artifacts-dir=test-results/myzowe-sdk-jwt-zaas-httpclient-optimized-20concurrent
# bzt taurus_config.yml -o settings.artifacts-dir=test-results/prodzowe-sdk-jwt
