serviceId: hellospring
title: Hello Spring REST API
description: Example for exposing a Spring REST API
baseUrl: http://localhost:10020/hellospring
homePageRelativeUrl:
statusPageRelativeUrl: /application/info
healthCheckRelativeUrl: /application/health
discoveryServiceUrls:
    - https://localhost:10011/eureka
ssl:
    verifySslCertificatesOfServices: true
    protocol: TLSv1.2
    keyAlias: localhost
    keyPassword: password
    keyStore: ../keystore/localhost/localhost.keystore.p12
    keyStorePassword: password
    keyStoreType: PKCS12
    trustStore: ../keystore/localhost/localhost.truststore.p12
    trustStorePassword: password
    trustStoreType: PKCS12
routes:
    - gatewayUrl: api/v1
      serviceUrl: /hellospring/api/v1
    - gatewayUrl: api/v1/api-doc
      serviceUrl: /hellospring/api-doc
apiInfo:
    title: Hello World Spring
    description: REST API for a Spring Application
    version: 1.0.0
catalogUiTile:
    id: cademoapps
    title: Sample API Mediation Layer Applications
    description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
    version: 1.0.0
