serviceId: enablerjavasampleapp
title: Onboarding Enabler Java Sample App
description: Example for exposing a Jersey REST API using Onboarding Enabler Java
baseUrl: https://localhost:10016/enablerJavaSampleApp
serviceIpAddress: 127.0.0.1

homePageRelativeUrl:
statusPageRelativeUrl: /application/info
healthCheckRelativeUrl: /application/health

discoveryServiceUrls:
    - https://localhost:10011/eureka

routes:
    - gatewayUrl: api/v1
      serviceUrl: /enablerJavaSampleApp/api/v1
    - gatewayUrl: ui/v1
      serviceUrl: /

apiInfo:
    - apiId: zowe.apiml.enabler.java.sample
      gatewayUrl: api/v1
      swaggerUrl: https://localhost:10016/enablerJavaSampleApp/openapi.json

catalog:
    tile:
        id: cademoapps
        title: Sample API Mediation Layer Applications
        description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
        version: 1.0.0

ssl:
    verifySslCertificatesOfServices: true
    protocol: TLSv1.2
    keyAlias: localhost
    keyPassword: password
    keyStore: ../keystore/localhost/localhost.keystore.p12
    keyStorePassword: password
    keyStoreType: PKCS12
    trustStore: ../keystore/localhost/localhost.truststore.p12
    trustStorePassword: password
    trustStoreType: PKCS12
