# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Testing

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:


    CITestsDocker:
        runs-on: ubuntu-latest
        timeout-minutes: 20

        container:
            image: ubuntu:latest

        services:
            api-catalog-services:
                image: 'ghcr.io/balhar-jakub/api-catalog-services'
                ports:
                    - 10014:10014
            caching-service:
                image: 'ghcr.io/balhar-jakub/caching-service'
                ports:
                    - 10016:10016
            discoverable-client:
                image: 'ghcr.io/balhar-jakub/discoverable-client'
                ports:
                    - 10012:10012
            discovery-service:
                image: 'ghcr.io/balhar-jakub/discovery-service'
                ports:
                    - 10011:10011
            gateway-service:
                image: 'ghcr.io/balhar-jakub/gateway-service'
                ports:
                    - 10010:10010
            mock-zosmf:
                image: 'ghcr.io/balhar-jakub/mock-zosmf'
                ports:
                    - 10013:10013


        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
           -    name: Set up Node
                uses: actions/setup-node@v2
                with:
                    node-version: '14'
           -    name: Get logs of the created docker services
                run: |
                    docker ps
