name: Conformant Containers - Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    IMAGE_BASE_DIR: ./containers

jobs:
    build:
        strategy:
            matrix:
                arch: [ amd64, s390x ]
                os: [ ubuntu, ubi ]
                include:
                    -   os: ubuntu
                        BUILD_ARG_LIST: ZOWE_BASE_IMAGE=latest-ubuntu
                    -   os: ubi
                        BUILD_ARG_LIST: ZOWE_BASE_IMAGE=latest-ubi

        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Cache Gradle packages
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle001-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle001-
            -   name: Cache Node.js modules
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.npm
                    key: ${{ runner.OS }}-node001-${{ hashFiles('**/package-lock.json, **/package.json') }}
                    restore-keys: |
                        ${{ runner.OS }}-node001-

            -   uses: zowe-actions/shared-actions/envvars-global@main

            -   uses: zowe-actions/shared-actions/docker-prepare@main
                with:
                    registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
                    registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
                    release: false
                    base-directory: ${{ env.IMAGE_BASE_DIR }}
                    image-name: gateway-service
                    linux-distro: ${{ matrix.os }}
                    cpu-arch: ${{ matrix.arch }}
                    # Used only for UBI
                    redhat-registry: ${{ env.DEFAULT_REDHAT_DOCKER_REGISTRY }}
                    redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
                    redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}

            -   name: Build amd64
                if: matrix.arch == "amd64"
                uses: zowe-actions/shared-actions/docker-build-local@main
                with:
                    build-arg-list: ${{ matrix.BUILD_ARG_LIST }}
                timeout-minutes: 5

            -   name: Build s390x
                if: matrix.arch == "s390x"
                uses: zowe-actions/shared-actions/docker-build-zlinux@main
                with:
                    zlinux-host: ${{ secrets.ZLINUX_HOST }}
                    zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
                    zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
                    zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
                    build-arg-list: ${{ matrix.BUILD_ARG_LIST }}
                    ### Only for UBI
                    redhat-registry: ${{ env.DEFAULT_REDHAT_DOCKER_REGISTRY }}
                    redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
                    redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
                timeout-minutes: 10

    define-manifests:
        needs:
            - build
        strategy:
            matrix:
                os: [ ubuntu, ubi ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   uses: zowe-actions/shared-actions/prepare-workflow@main

            -   uses: zowe-actions/shared-actions/docker-prepare@main
                with:
                    registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
                    registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
                    release: false
                    base-directory: ${{ env.IMAGE_BASE_DIR }}
                    image-name: gateway-service
                    linux-distro: ${{ matrix.os }}

            -   uses: zowe-actions/shared-actions/docker-manifest@main
                with:
                    linux-distro: ${{ matrix.os }}
                    cpu-arch-list: "amd64 s390x"
                timeout-minutes: 2

