name: Containers - Build, Test

on:
    push:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    pull_request:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
    PublishJibContainers:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}
            -   uses: ./.github/actions/setup
            -   name: Build with Gradle
                run: >
                    ./gradlew clean jib -x test -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }} -Pzowe.docker.password=${{ secrets.PERSONAL_JB_TOKEN }} -Pzowe.docker.username=balhar-jakub -Pzowe.docker.container=ghcr.io/balhar-jakub/ -Pzowe.docker.tag=${{ env.JOB_ID }}
            -   name: Standalone Catalog
                run: >
                    ./gradlew :api-catalog-services:jib -Pzowe.jib.image.suffix=standalone -Pzowe.jib.image.javaAgentPort=6305 -Pzowe.jib.image.debugPort=5125 -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }} -Pzowe.docker.password=${{ secrets.PERSONAL_JB_TOKEN }} -Pzowe.docker.username=balhar-jakub -Pzowe.docker.container=ghcr.io/balhar-jakub/ -Pzowe.docker.tag=${{ env.JOB_ID }}

            -   uses: ./.github/actions/teardown

    CITestsGatewayRegisterToMultipleClusters:
        needs: PublishJibContainers
        container: ubuntu:latest
        runs-on: ubuntu-latest
        timeout-minutes: 15

        services:
            api-catalog-services:
                image: ghcr.io/balhar-jakub/api-catalog-services:${{ github.run_id }}-${{ github.run_number }}
                volumes:
                    - /api-defs:/api-defs
            caching-service:
                image: ghcr.io/balhar-jakub/caching-service:${{ github.run_id }}-${{ github.run_number }}
            discoverable-client:
                image: ghcr.io/balhar-jakub/discoverable-client:${{ github.run_id }}-${{ github.run_number }}
            mock-services:
                image: ghcr.io/balhar-jakub/mock-services:${{ github.run_id }}-${{ github.run_number }}
            discovery-service:
                image: ghcr.io/balhar-jakub/discovery-service:${{ github.run_id }}-${{ github.run_number }}
                volumes:
                    - /api-defs:/api-defs
            discovery-service-2:
                image: ghcr.io/balhar-jakub/discovery-service:${{ github.run_id }}-${{ github.run_number }}
                volumes:
                    - /api-defs:/api-defs
                env:
                    APIML_SERVICE_HOSTNAME: discovery-service-2
            gateway-service:
                image: ghcr.io/balhar-jakub/gateway-service:${{ github.run_id }}-${{ github.run_number }}

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Run CI Test against Gateway that registers to 2 separated(not aware of each other) Discovery services
                run: >
                    ./gradlew :integration-tests:runContainerTests --info
                    -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}

            # Coverage results are not stored in this job as it would not provide much additional data
            -   name: Store results
                uses: actions/upload-artifact@v2
                if: always()
                with:
                    name: CITestsGatewayRegisterToMultipleClusters-${{ env.JOB_ID }}
                    path: |
                        integration-tests/build/reports/**

            -   uses: ./.github/actions/teardown
