name: Containers - Build, Test

on:
    push:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    pull_request:
        branches: [ v2.x.x ]
        paths-ignore:
            - '**.md'
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
    PublishJibContainers:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build with Gradle
                run: >
                    ./gradlew jib -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }} -Pzowe.docker.password=${{ secrets.PERSONAL_JB_TOKEN }} -Pzowe.docker.username=balhar-jakub -Pzowe.docker.container=ghcr.io/balhar-jakub/ -Pzowe.docker.tag=${{ env.JOB_ID }}

            -   uses: ./.github/actions/teardown

    CloudGatewayServiceRouting:
        needs: PublishJibContainers
        runs-on: ubuntu-latest
        container: ubuntu:latest
        timeout-minutes: 10

        services:
            discovery-service:
                image: ghcr.io/balhar-jakub/discovery-service:${{ github.run_id }}-${{ github.run_number }}
            gateway-service:
                image: ghcr.io/balhar-jakub/gateway-service:${{ github.run_id }}-${{ github.run_number }}
            cloud-gateway-service:
                image: ghcr.io/balhar-jakub/cloud-gateway-service:${{ github.run_id }}-${{ github.run_number }}
                env:
                    APIML_SERVICE_GATEWAY_PROXY_ENABLED: false
            discoverable-client:
                image: ghcr.io/balhar-jakub/discoverable-client:${{ github.run_id }}-${{ github.run_number }}

        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Run CI Tests
                run: >
                    ./gradlew :integration-tests:runCloudGatewayServiceRoutingTest --info -Denvironment.config=-docker -Denvironment.offPlatform=true
                    -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}

            -   name: Dump CGW jacoco data
                run: >
                    java -jar ./scripts/jacococli.jar dump --address cloud-gateway-service --port 6310 --destfile ./results/cloud-gateway-service.exec

            -   name: Store results
                uses: actions/upload-artifact@v2
                if: always()
                with:
                    name: CloudGatewayServiceRouting-${{ env.JOB_ID }}
                    path: |
                        integration-tests/build/reports/**
                        results/**

            -   uses: ./.github/actions/teardown
