name: Containers - Build, Test

on:
    push:
        branches: [ master, v2.x.x ]
    pull_request:
        branches: [ master, v2.x.x ]
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
    PublishJibContainers:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build with Gradle
                run: >
                    ./gradlew jib -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }} -Pzowe.docker.password=${{ secrets.PERSONAL_JB_TOKEN }} -Pzowe.docker.username=balhar-jakub -Pzowe.docker.container=ghcr.io/balhar-jakub/ -Pzowe.docker.tag=${{ github.event.pull_request.number || 'latest' }}

            -   uses: ./.github/actions/teardown

    CITestsWithInfinispan:
        needs: PublishJibContainers
        runs-on: ubuntu-latest
        container: ubuntu:latest
        timeout-minutes: 15

        services:
            api-catalog-services:
                image: ghcr.io/balhar-jakub/api-catalog-services:${{ github.event.pull_request.number || 'latest' }}
                volumes:
                    - /api-defs:/api-defs
            caching-service:
                image: ghcr.io/balhar-jakub/caching-service:${{ github.event.pull_request.number || 'latest' }}
                env:
                    ZWE_CACHING_SERVICE_PERSISTENT: 'infinispan'
                    JGROUPS_BIND_PORT: "7099"
                    SERVER_SSL_KEYSTORETYPE: "PKCS12"
                    CACHING_STORAGE_INFINISPAN_PERSISTENCE_DATALOCATION: "data_replica"
                    CACHING_STORAGE_INFINISPAN_INITIALHOSTS: "caching-service-2[7098]"
                    CACHING_STORAGE_MODE: "infinispan"
                    APIML_SERVICE_PORT: "10022"
                    JGROUPS_BIND_ADDRESS: "caching-service"

            caching-service-2:
                image: ghcr.io/balhar-jakub/caching-service:${{ github.event.pull_request.number || 'latest' }}
                env:
                    ZWE_CACHING_SERVICE_PERSISTENT: 'infinispan'
                    JGROUPS_BIND_PORT: "7098"
                    SERVER_SSL_KEYSTORETYPE: "PKCS12"
                    CACHING_STORAGE_INFINISPAN_PERSISTENCE_DATALOCATION: "data"
                    CACHING_STORAGE_INFINISPAN_INITIALHOSTS: "caching-service[7099]"
                    CACHING_STORAGE_MODE: "infinispan"
                    JGROUPS_BIND_ADDRESS: "caching-service-2"
                    APIML_SERVICE_HOSTNAME: "caching-service-2"

            discoverable-client:
                image: ghcr.io/balhar-jakub/discoverable-client:${{ github.event.pull_request.number || 'latest' }}
            discovery-service:
                image: ghcr.io/balhar-jakub/discovery-service:${{ github.event.pull_request.number || 'latest' }}
                volumes:
                    - /api-defs:/api-defs
            gateway-service:
                image: ghcr.io/balhar-jakub/gateway-service:${{ github.event.pull_request.number || 'latest' }}
            mock-services:
                image: ghcr.io/balhar-jakub/mock-services:${{ github.event.pull_request.number || 'latest' }}
                env:
                    ZOSMF_APPLIEDAPARS: AuthenticateApar

        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build with Gradle
                run: >
                    ./gradlew :integration-tests:runCachingServiceTests --info -Denvironment.config=-docker -Denvironment.offPlatform=true
                    -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}

            -   uses: ./.github/actions/dump-jacoco
                if: always()

            -   name: Store results
                uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: CITestsWithInfinispan-${{ env.JOB_ID }}
                    path: |
                        integration-tests/build/reports/**
                        results/**

            -   uses: ./.github/actions/teardown
