name: Containers - Build, Test

on:
    push:
        branches: [ master, v2.x.x ]
    pull_request:
        branches: [ master, v2.x.x ]
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:

    Oauth2Integration:
        runs-on: ubuntu-latest
        container: ubuntu:latest
        timeout-minutes: 10
        services:
            discoverable-client:
                image: ghcr.io/balhar-jakub/discoverable-client:${{ github.event.pull_request.number || 'latest' }}
                env:
                    OKTA_OAUTH2_ISSUER: https://dev-95727686.okta.com/oauth2/default
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Run CI Tests
                run: >
                    ./gradlew :integration-tests:runOauth2Tests --info -Denvironment.config=-docker -Denvironment.offPlatform=true -Dokta.client.id=${{ secrets.OKTA_CLIENT_ID }} -Dokta.client.password=${{ secrets.OKTA_CLIENT_PASSWORD }}
                    -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}

            -   uses: ./.github/actions/teardown
