# This workflow will create images for api-layer services
# This workflow is only used to expose build-conformant-images.yml in a way that doesn't give users the option to release.
name: Create Image Only (No Release)

on:
    workflow_dispatch:
        inputs:
            service:
                description: 'Enter a service name for which to create an image. The name must match a directory in /containers. E.g. gateway-service or discovery-service. If skipped, images will be created for all services.'
                required: false
                default: 'all'

jobs:
    build-images-all-services:
        uses: zowe/api-layer/.github/workflows/build-conformant-images.yml@apiml/GH1988/concurrent_container_builds # TODO switch to master
        with:
            service: ${{ github.event.inputs.service }}
            release: false
        secrets:
            registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
            registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
            redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
            redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
            zlinux-host: ${{ secrets.ZLINUX_HOST }}
            zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
            zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
            zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
