name: Release new image version (specific)

on:
    workflow_dispatch:
        inputs:
            release_version:
                description: 'The version that is going to be release'
                required: true
            new_version:
                description: 'The version that should be used as a new one after the release.'
                required: true

jobs:
    publish-images:
        uses: zowe/api-layer/.github/workflows/build-conformant-images.yml@master
        with:
            version: ${{ github.event.inputs.release_version }}
        secrets:
            registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
            registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
            redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
            redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
            zlinux-host: ${{ secrets.ZLINUX_HOST }}
            zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
            zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
            zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
