name: "Merge on major version"

on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
    merge:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Merge branch
                uses: oddbit/action-branch-merge@master
                with:
                    target_branch: 'v2.x.x'
                    source_branch: 'master'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
