# This workflow will release project with Gradle
name: Release new version (automated)

on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron:  '0 0 * * 5'
    workflow_dispatch:
        inputs:
            scope:
                description: 'Specify scope that is to be used. The options are patch, minor, major'
                required: true
                default: 'patch'

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 40

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

            - uses: ./.github/actions/setup

            - name: Build with Gradle
              run: ./gradlew build

            - name: Clean git
              run: git reset --hard HEAD

            - name: Set email
              run: git config user.email "zowe-robot@users.noreply.github.com"

            - name: Set name
              run: git config user.name "Zowe Robot"

            - name: Release to NPM automatic
              run: |
                  cd onboarding-enabler-nodejs
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                  echo "registry=$DIST_REGISTRY" >> ~/.npmrc
                  npm version ${{ github.event.inputs.scope || env.DEFAULT_SCOPE }}
                  npm publish --access public
                  git add package.json
                  git commit -m "Update version"
                  git push
                  cd ..
              env:
                  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
                  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
                  DEFAULT_SCOPE: 'patch'
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  DIST_REGISTRY: https://registry.npmjs.org/

            - name: Release with Gradle automatic
              run: ./gradlew release -x test -x checkstyleTest -Prelease.useAutomaticVersion=true -Prelease.scope=${{ github.event.inputs.scope || env.DEFAULT_SCOPE }} -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_USERNAME
              env:
                  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
                  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
                  DEFAULT_SCOPE: 'patch'

            - uses: ./.github/actions/teardown

    release-images:
        uses: zowe/api-layer/.github/workflows/build-conformant-images.yml@master
        with:
            release: true
        secrets:
            registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
            registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
            redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
            redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
            zlinux-host: ${{ secrets.ZLINUX_HOST }}
            zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
            zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
            zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
