name: "Flag the PRs touching security related code"

on:
    pull_request:
        branches: [ master ]

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - id: files
              uses: jitterbit/get-changed-files@v1
            - run: |
                  for changed_file in ${{ steps.files.outputs.all }}; do
                    echo "Do something with this ${changed_file}."
                  done


    # How do I get files changed in PR

# How do I recognize such files are security related? // Easy to do locally
  # Baseline is that we know that some files are security related
  # Next step is that we know of some packages that are risky and that we may look at files using e.g. spring security classes
