name: "Flag the PRs touching security related code"

on:
    pull_request:
        branches: [ master, v2.x.x ]

jobs:
    analyze:
        name: Identify security related PR
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup and run the node
              run: |
                  cd scripts/security_sensitive
                  npm install
                  node index.js zowe api-layer ${{ github.event.pull_request.number }} ${{ secrets.ZOWE_ROBOT_TOKEN }}
                  cd ..
